apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: hospital-portal
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: kong
        image: kong:3.4-alpine
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/kong/declarative/kong.yml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000"
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8001
          name: admin
        volumeMounts:
        - name: kong-config
          mountPath: /kong/declarative
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: kong-config
        configMap:
          name: kong-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: hospital-portal
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 8000
    name: proxy
  - port: 8001
    targetPort: 8001
    name: admin
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: hospital-portal
data:
  kong.yml: |
    _format_version: "3.0"
    
    services:
    - name: hospital-service
      url: http://hospital-service:3003
      routes:
      - name: hospital-api
        paths:
        - /api/v1/hospitals
        - /api/v1/hospitals/health
        strip_path: false
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
    
    plugins:
    - name: rate-limiting
      config:
        minute: 100
        hour: 1000
    - name: cors
      config:
        origins:
        - "https://hospital-portal.com"
        - "https://staging.hospital-portal.com"
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
        headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
        credentials: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: hospital-portal
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.hospital-portal.com
    secretName: api-gateway-tls
  rules:
  - host: api.hospital-portal.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80
