apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: healthwallet
data:
  NODE_ENV: "production"
  PORT: "3001"
  MONGODB_URI: "mongodb://admin:password123@mongodb:27017/healthwallet?authSource=admin"
  REDIS_URL: "redis://:redis123@redis:6379"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  JWT_EXPIRES_IN: "24h"
  BLOCKCHAIN_RPC_URL: "http://ganache:8545"
  IPFS_URL: "http://ipfs:5001"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: healthwallet
type: Opaque
data:
  BLOCKCHAIN_PRIVATE_KEY: eW91ci1wcml2YXRlLWtleS1oZXJl  # your-private-key-here
  AWS_ACCESS_KEY_ID: eW91ci1hd3MtYWNjZXNzLWtleQ==  # your-aws-access-key
  AWS_SECRET_ACCESS_KEY: eW91ci1hd3Mtc2VjcmV0LWtleQ==  # your-aws-secret-key

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: healthwallet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: healthwallet/backend:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: healthwallet
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: healthwallet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
