apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: securehealth
  labels:
    app: api-gateway
    component: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        component: gateway
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: kong
        image: kong:3.4-alpine
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8443
          name: https
        - containerPort: 8001
          name: admin
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/kong/kong.yml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        volumeMounts:
        - name: kong-config
          mountPath: /kong
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: kong-config
        configMap:
          name: kong-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: securehealth
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: admin
  selector:
    app: api-gateway
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: securehealth
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    - name: auth-service
      url: http://auth-service:3001
      routes:
      - name: auth-routes
        strip_path: true
        paths:
        - /auth
        plugins:
        - name: rate-limiting
          config:
            minute: 100
            hour: 1000
        - name: cors
          config:
            origins: ["*"]
            methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            headers: ["Accept", "Authorization", "Content-Type", "X-Requested-With"]
            exposed_headers: ["X-Auth-Token"]
            credentials: true
            max_age: 3600

    - name: document-service
      url: http://document-service:3002
      routes:
      - name: document-routes
        strip_path: true
        paths:
        - /documents
        plugins:
        - name: rate-limiting
          config:
            minute: 50
            hour: 500
        - name: request-size-limiting
          config:
            allowed_payload_size: 50

    - name: hospital-service
      url: http://hospital-service:3003
      routes:
      - name: hospital-routes
        strip_path: true
        paths:
        - /hospitals
        plugins:
        - name: rate-limiting
          config:
            minute: 200
            hour: 2000

    - name: patient-service
      url: http://patient-service:3004
      routes:
      - name: patient-routes
        strip_path: true
        paths:
        - /patients
        plugins:
        - name: rate-limiting
          config:
            minute: 100
            hour: 1000

    - name: blockchain-adapter
      url: http://blockchain-adapter:3005
      routes:
      - name: blockchain-routes
        strip_path: true
        paths:
        - /blockchain
        plugins:
        - name: rate-limiting
          config:
            minute: 30
            hour: 300

    - name: claims-service
      url: http://claims-service:3006
      routes:
      - name: claims-routes
        strip_path: true
        paths:
        - /claims
        plugins:
        - name: rate-limiting
          config:
            minute: 50
            hour: 500

    plugins:
    - name: prometheus
      config:
        per_consumer: true
        status_code_metrics: true
        latency_metrics: true
        bandwidth_metrics: true
        upstream_health_metrics: true

    - name: security-headers
      config:
        headers:
        - "X-Frame-Options: DENY"
        - "X-Content-Type-Options: nosniff"
        - "X-XSS-Protection: 1; mode=block"
        - "Strict-Transport-Security: max-age=31536000; includeSubDomains"
        - "Referrer-Policy: strict-origin-when-cross-origin"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: securehealth
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  tls:
  - hosts:
    - api.securehealth.app
    - hospital.securehealth.app
    secretName: securehealth-tls
  rules:
  - host: api.securehealth.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80
  - host: hospital.securehealth.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80

